[build]
  command = "bun run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@libsql/client",
    "libsql",
    "@libsql/linux-x64-gnu",
    "@libsql/linux-x64-musl"
  ]
  included_files = ["package.json"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
